### PR TITLE
better readable IBAN

### PR DESCRIPTION
**Pull request by twothreenine**
Display IBANs in groups of 4 digits with whitespaces in between
solves #821 
I changed it in various views I could find.
Important note: I couldn't test it for finance/bank_transactions/show.html.haml
Also I'm very new to Ruby, so please check it carefully

### CODE REVIEW

**Comment by paroga** [comment]
cool, thanks for the PR.
one problem with your change is, that it's then not possible to just double-click it to mark it for copy&paste. to solve this you could add a "Copy to clipboard"-button or use some little CSS-tricks (as described in the [German Wikipedia](https://de.wikipedia.org/wiki/Internationale_Bankkontonummer#Schreibweise)).

if the generated HTML looks like
```html
<span class="iban">
<span>DE07</span><span>1234</span><span>1234</span><span>1234</span><span>1234</span>12
</span>
```
you could format it with the following CSS to add some padding:
```css
.iban > span {
  margin-right: 0.5em;
}
```
As long as there is no whitespace between the different `<span>` elements, it can be still double-clicked.

what do you think about that?

**Comment by fruestueck** [comment]
Your already working on this? Awesome!

> if the generated HTML looks like
> 
> ```
> <span class="iban">
> <span>DE07</span><span>1234</span><span>1234</span><span>1234</span><span>1234</span>12
> </span>
> ```

Agreed. This is also preferrable as it would avoid introduction of whitespaces. Whitespaces could break insertion into banking forms (due to the character limit, and or bad support for whitespace within the iban)

**Comment by twothreenine** [comment]
I managed to implement that and it works for the most pages, however when you copy an IBAN from the suppliers/show page, four whitespaces appear in front of it ("    AT1234123...") regardless of how many margins there are within the number.
I don't know how to fix this.
Also again I couldn't test it for finance/bank_accounts/index and finance/bank_transactions/show.

**Comment by paroga** [comment]
> when you copy an IBAN from the suppliers/show page, it contains four whitespaces

I looks like a wired CSS effect to me, which we could just ignore for now, since it's very uncommon that people will try to copy the IBAN there.

`finance/bank_accounts/index` and `finance/bank_transactions/show` worked for me too.

**Pull request merged**
