### PR TITLE
Gemfile: bundle update gave error as git branch of gem "inherited_resources" doesn't exists any more

### PR DESCRIPTION
**Pull request by marcopenhacking**
This helped me fixing a bundle update error (see details). Maybe this is helpful.

### CODE REVIEW

**Comment by wvengen** [comment]
Ouch, that's not good! I'll check if we can use the normal [gem](https://rubygems.org/gems/inherited_resources) nowadays.

**Comment by wvengen** [comment]
I'll do a 4.4.1 release after this, because it prevents people from installing Foodsoft.

**Comment by wvengen** [comment]
It works with the upstream gem :)

p.s. when updating `Gemfile`, you need to run `bundle install` and commit `Gemfile.lock` as well. That's what the CI error is caused by.

**Comment by marcopenhacking** [comment]
Thanks, update to 4.4.1 worked like a charm.

**Pull request closed without merging**
