### PR TITLE
allow all users to see article list (but not edit).  case insensitive…

### PR DESCRIPTION
**Pull request by carchrae**
i want everyone in my co-op to be able to view the catalogues for each supplier.  this allows that.  it also adds a case insensitive search on article name and number.

### CODE REVIEW

**Comment by wvengen** [comment]
I think it's fine if everyone can see the whole article list
Do others agree?

**Comment by carchrae** [comment]
the only possible objection (to object to myself) is that there is currently no way to see an index of the all suppliers.  in our co-op, i paste the link to a particular supplier into the email, but perhaps it would be good to have the supplier `index` page also have the same modification.  and likewise, add it to the navigation.

in our co-op we do this so people can see the whole catalog and make requests.

**Comment by wvengen** [comment]
> There is currently no way to see an index of the all suppliers.

Hah, that's a good point :) I think it would be good to have the supplier index page accessible to all users, and indeed add it to the navigation. Maybe we'll need to revisit the navigation at some point, but let's look at that later then, when needed.

**Comment by wvengen** [comment]
I've [asked](http://foodsoft.51229.x6.nabble.com/Shall-we-make-suppliers-and-articles-visible-for-all-users-by-default-td2127.html) the foodsoft-discuss mailing-list if this change is ok.

**Comment by wvengen** [comment]
The mailing-list responded that we shouldn't show article prices by default, this can be sensitive.
Let's make this optional (I guess sharedlists would be something to add later).

**Comment by carchrae** [comment]
ok, so if i add a` FoodsoftConfig` setting, that would work?

**Comment by wvengen** [comment]
Yes!

**Comment by yksflip** [comment]
Hey,
this look's stale to me, is this still relevant?
If so, please feel free to reopen this!

**Pull request closed without merging**
