### PR TITLE
Add BESTELLEN_EN.md

### PR DESCRIPTION
**Pull request by alex-quiterio**
WIP

### CODE REVIEW

**Comment by paroga** [comment]
Thanks for the PR! I'd prefer to add new texts to the [documentation](https://foodcoops.readthedocs.io/en/latest/) in the [user-docs](https://github.com/foodcoops/user-docs) repository.

**Comment by wvengen** [comment]
@paroga I agree, for user/foodcoop-documentation. This document is kind of both: an intro for developers wanting to delve into the code, a very minimal specification, and reference documentation for users/foodcoops.
Somehow I think that having to keep this doc in sync with the algorithm would be good, and easier to do when it is in this repo.
That being said, I can live with both. What do you think, @paroga?

**Comment by paroga** [comment]
if the target audience are developers, i agree that it should go into this repository, but i doesn't look like that to me. i'd redirect developers who need a basic overview about what foodsoft does to the user documentation. i see no value in duplicating that. i personally would favor removing the existing `BESTELLEN.md` (we should remove the remaining german texts anyway) instead

**Comment by wvengen** [comment]
Good, let's move it to user-docs.
The integration spec already covers the need for making sure the algorithm keeps working correctly.

**Comment by wvengen** [comment]
@alex-quiterio care to open a PR there, please?

**Pull request closed without merging**
