### PR TITLE
Allow to copy articles

### LINKED ISSUE #541: Copy this article and add as new after edit.
When entering articles from the website it would be great if you can copy one article to create the next, as many times for example I have articles in 1L and 5L bottles and I have to enter the same values again in most of the form.

### PR DESCRIPTION
**Pull request by JuliusR**
Fixes #541.

### CODE REVIEW

**Comment by JuliusR** [comment]
The article index already offers "edit" and "delete" buttons. This pull request adds a third button in between.

As a disadvantage, the table becomes even wider. I am not sure if this pull requests improves or worsens the usability on average. What do you think?

**Comment by wvengen** [comment]
Could you make a screenshot (perhaps even of different window widths)?

**Comment by JuliusR** [comment]
| Width in px | without copy | with copy |
|-|-|-|
| 375 |  375-without | 375-with |
| 800 | 800-without | 800-with |
| 1024 | 1024-without | 1024-with |
| 1280 | 1280-without | 1280-with |
| 1600 | 1600-without | 1600-with |

**Comment by JuliusR** [comment]
After looking at it more carefully, I am not so much bothered about the wide tables. It seems that the real difficulty are the "line breaks" between the buttons. This increases the table row height and leads to a small vertical spacing of buttons. With my mouse, I can safely point on one of them, but what about touchscreen devices?

We can prevent the buttons from "line breaking" by putting them in separate columns, but that would always reserve lots of space for the buttons. We should also consider languages where "edit", "copy", and "delete" have more characters.

What are your thoughts?

**Comment by f0k** [comment]
> It seems that the real difficulty are the "line breaks" between the buttons. 
> [...]
> We should also consider languages where "edit", "copy", and "delete" have more characters.
>
> What are your thoughts?

edit duplicate delete

**Comment by wvengen** [comment]
Ah, it's buttons breaking over the line is even better now, I'd say.
Icons may be nice, especially if we do it consistenly across the app.
Fine for now, I'd say.

**Comment by JuliusR** [comment]
I agree that we can merge this, and we can introduce icons later (if desired).

**Pull request merged**
