### PR TITLE
Improved Docker Setup

### PR DESCRIPTION
**Pull request by bennibu**
* Use ruby version 3 with most dependencies already shipped
* Use bundle container
* Run rails commands as app user
* Set Database encoding

Sadly, I couldn't get the test suite to run without some errors. But I guess, this has nothing to do with the docker update as there are also errors in latest travis build.

### CODE REVIEW

**Comment by wvengen** [comment]
Thanks, looks good! I'll test and merge (tests are currently broken - oops - #400).

**Comment by bennibu** [comment]
@wvengen I forgot to mention. If you have to migrate from the old docker setup be sure to delete old container stuff `(sudo) rm -rf tmp/* log/*` and rebuild the container with `docker-compose build`. Otherwise rails will fail upon missing permissions (in tmp and log files).

**Comment by wvengen** [comment]
Tested and merged, thanks!

**Comment by wvengen** [comment]
Oh, and I added your notice to the CHANGELOG, so people will (hopefully) catch it when upgrading.

**Comment by bennibu** [comment]
Thanks!

**Pull request closed without merging**
