### PR TITLE
Various stuff

### PR DESCRIPTION
**Pull request by paroga**
I've done my changes in one PR this time, since there are a lot of schema changes. It would be great if you could cherry-pick pick commits if you do not accept the whole PR. I'll rebase it then.

### CODE REVIEW

**Comment by wvengen** [comment]
This is great, thanks a lot! I'll look into it in more detail later.
First thing is #400 I guess :o

**Comment by paroga** [comment]
FYI: The Travis build is now failing because libmagic-dev is not installed. Where is the best place to put the apt call? (I didn't find other apt calls by a quick search)

**Comment by wvengen** [comment]
regarding the Travis build: you can add `libmagic-dev` below the new `metacity` line. Hope Travis has whitelisted it.

**Comment by wvengen** [comment]
Wow ... that's a lot! Awsome :)
But is it possible so split it up a bit, please? The discussion may become a bit much and confusing, I'm afraid, with so many things in this single place.
If that's too much work, I can look through it and identify the things that I'd be happy to merge first.

**Comment by paroga** [comment]
I'd prefere different PR as well, but then I get lot of merge conflicts because of the schema changes. We had that already....
I tried to keep the different commits as logical changes as good as possible.
It would be great if you could do one review of the big stuff and cherry-pick the finished stuff (some of the changes are old PR). For the remaining stuff I can create different PR, but then there will be the overhead with the schema...

**Comment by wvengen** [comment]
I've cherry-picked picked some simple fixes. I must admit it looks a bit overwhelming. It would really help me if you could create a list of commits that belong together and add a little explanation, e.g. like this - it would really help me to pick this up bit by bit.

- [ ] Add messagegroups b895b70
- [ ] Soft-delete user (because as a foodcoop admin, I'd like to see who sent messages after users have left) 57c509d
- [ ] Invoices
  - [ ] Store who created the invoice 9958514
  - [ ] Allow invoices to be linked to multiple orders (datamodel) c08033b
  - [ ] Add invoices role 64873ff
  - [ ] Attachments for invoices 8079b74
  - [ ] etc.

**Comment by paroga** [comment]
There are a bunch of simple fixes you did not pick (e.g. "Order items in select boxes"), so I'm not sure if you at lest gone trough all commits. ;-) Not sure how do you want to group me that stuff. What do you think about a short call?

**Comment by wvengen** [comment]
Thanks for your reply. True, I haven't looked at everything yet.
The checkbox list above was just an incomplete example of the format that would help review. Grouping would be for issues that belong to a feature(set) or epic. Stuff you might put in a single pull request. Something I can review separately (without needing to go through all other commits to see if they are related). Calling is not convenient for me at the moment (in the course of next week could be possible).

**Comment by paroga** [comment]
could you do a quick go-trough and cherry-pick the simple fixes? if you done that i'll create separate PRs for the rest, but you have to resolve the merge conflicts then (or i do not commit the schema file and you create it during cherry-picking)

**Comment by paroga** [comment]
just ignore the changes which you find "too complex" and cherry-pick the easy ones

**Comment by wvengen** [comment]
Thanks, I will! You can indeed just leave out the schema changes.

**Comment by wvengen** [comment]
Pending for cherry-picking:
- [ ] 8079b74 invoice attachments (after documents #353)
- [ ] 4263200b7f07f9efa4b7ac5d6547932708e2a21a more invoice info
- [ ] 2a3d2a9 add ordergroup name to GroupOrder
- [ ] d93d4fc add stock articles to order -- need to ponder the concept

I'd like to see new PRs for
- a2a630b break for ordergroup --> #404
- af63261e35b9f10f0f4ac5707476dc4c9eb52edb pickup date
- documents #353 
- bdeb0b1ce5ce9b53afb618082221125816ea04f6 7660c454e947bb7586db85f2469bb5fecb80f8e5 7bdb192f3c274e21a8a60ace864f2124ce429fd9 83681dcf7667962d2424f4db054e78d069271dcc bank-related

The rest is integrated. Thanks a lot, it's quite impressive!

**Comment by wvengen** [comment]
I'd just like to mention that our test coverage moved from 75% to 60% in the last week, and will go to 50% when the financial transaction changes are merged.

**Comment by wvengen** [comment]
All of is either integrated or work in progress in another PR.

**Pull request closed without merging**
