### PR TITLE
Use a temporary mysql-server for assets precompilation during Docker …

### PR DESCRIPTION
**Pull request by paroga**
…build

### CODE REVIEW

**Comment by wvengen** [comment]
Just came across [multi-stage builds](https://docs.docker.com/engine/userguide/eng-image/multistage-build/#use-multi-stage-builds), would that be an option for asset precompilation and bundle installation? First stage could install all dependencies needed for building and precompilation, second step would setup the final image and just copy the app directory to the new image. Just need to make sure to have a shared base system layer in the two build stages.

**Comment by paroga** [comment]
Yes, I'm aware of that, but AFAIK Docker Hub does not support this feature ATM. Only Docker Cloud does.

**Comment by wvengen** [comment]
The build is failing, though. I suspect Travis CI problems, but it would be good to mention that you've seen the build failing and why it is acceptable to merge anyway (!)

**Comment by paroga** [comment]
My fault, sty. I didn't look at this build result, just at the build results on hub.docker.comm, since it only affects the Docker build. But it seams that Travis is doing something with the Docker stuff. It also fails if I add the spec folder to the `.dockerignore` file. Do you know more how Travis is configured ATM?

**Comment by wvengen** [comment]
Weird, haven't seen this before. It looks like either the database creation command failed, or Travis changed the setup? [mysql on Travis docs](https://docs.travis-ci.com/user/database-setup/#MySQL)

**Comment by paroga** [comment]
Travis has now problems to build the same revision, which worked already before:
https://travis-ci.org/foodcoops/foodsoft/builds/260397329
https://travis-ci.org/foodcoops/foodsoft/builds/260541712

**Comment by wvengen** [comment]
It looks like something changed at Travis CI. Fixed it in af1243ebeae534722b69e4f537e096f4ebafac63.

**Pull request merged**
