### PR TITLE
Added Turkish support with help of ChatGPT

### PR DESCRIPTION
**Pull request by nurp**

### CODE REVIEW

**Comment by wvengen** [comment]
Thank you for your translation!

As a general translation thing: how much did you check the ChatGPT output? It requires care and thought to translate a user-interface well and consistently. An automated bot is not guaranteed to do this well, whatever AI you may use. Especially domain-specific terms (like "Ordergroup", "User", "Apple points", "Order", "Supplier", "Article", and more) usually need some thought.

Also, did you check how the translations look while running Foodsoft?
There used to be a translation instance of Foodsoft where your online translations could be viewed directly, but unfortunately we don't have this anymore. So it is important - especially for a first time full translation, to manually check how everything looks. Does it fit in the available space? Do terms make sense in context? Is the UI still understandable?

**Comment by nurp** [comment]
I looked and in general ChatGPT did a great work but I didn't check everything because my aim was to have a first version so that I can run it online to test drive with other volunteers and then release a fixed version for everything. 
I don't know any way other than running this Turkish version in Gitpod, and with Gitpod, it goes offline once I turn off my computer.
I'll ask foodcoops.net if they can pull a version from my fork, maybe then other Turkish collaborators can check with me.
For now, you can decline then.

**Comment by nurp** [comment]
I also didn't understand domain specific keywords. What should I look for, for "Ordergroup" for example? ChatGPT left those special keywords as they are. ie: 
description2: "%{ordergroups} %{article_count} adet ürün sipariş verdi,

**Comment by wvengen** [comment]
> I looked and in general ChatGPT did a great work but I didn't check everything because my aim was to have a first version so that I can run it online to test drive with other volunteers and then release a fixed version for everything.

:+1:

> I'll ask foodcoops.net if they can pull a version from my fork, maybe then other Turkish collaborators can check with me.

That will not be an option, foodcoops.net runs the latest stable version / master of Foodsoft.
Please feel free to suggest on the [forum](https://forum.foodcoops.net/) your need for hosting a version of Foodsoft for translating. If there are more users that want this, that increases chances that this will happen eventually. For now, I think you will need to arrange that yourself.

Great to hear you've run this with Foodsoft and looked at the UI :+1:

> I also didn't understand domain specific keywords. What should I look for, for "Ordergroup" for example? 

Yes. Translators often create list of terminology, how specific words/concepts are translated.
See https://foodcoops.readthedocs.io/en/latest/ for other documentation where you will find these concepts - though somehow they are sometimes named differently from what Foodsoft itself uses (e.g. cellar vs. stock).

Special keywords with a `%` sign indeed need to be retained, they are replaced with numbers or another (translated) text.

I suppose you've [seen the wiki on Translation](https://github.com/foodcoops/foodsoft/wiki/Translation).

**Comment by kidhab** [comment]
#995 was merged. I assume we can close this MR, can't we?

**Comment by kidhab** [comment]
You created another MR (#995) and that was merged. So if you close this one it's indeed a MR with unmerged commits. Do you want the changes from this MR also get merged? I assumed that the other changes are quite newer because you explicitly stated that you double checked your changes.

**Pull request closed without merging**
