### PR TITLE
fix searching in external article database (#772)

### PR DESCRIPTION
**Pull request by JuliusR**
Can we use this simple fix for #772 ?

### CODE REVIEW

**Comment by wvengen** [comment]
Thanks for finding the issue here! :100: 
Could this introduce a security issue?

**Comment by JuliusR** [comment]
> Could this introduce a security issue?

This is the correct question. I believe the answer is "no" because we are using the result for the following two purposes only:

- `highlight`ing the matched name parts in the view
- passing the query to ransack (where [`to_unsafe_h` is called right away](https://github.com/activerecord-hackery/ransack/blob/c9cc20de9e0f7bab92e0579c85bed64d614d23de/lib/ransack/search.rb#L18))

I perfectly agree that safety should be obvious, so my first attempt with `to_unsafe_h` is bad practice.

**Comment by JuliusR** [comment]
I updated the code to avoid `to_unsafe_h`. Could you have a look again please?

**Review by wvengen — APPROVED** [review]
Thank you, this cleans up the existing code too. Assuming you've tested this well, :+1:

**Comment by paroga** [comment]
Please rebase your commits when pushing them to master to avoid the useless merge commits, which make the history a lot less readable. The change in the rewritten history is now 4043433539f34b880bec8826d2f29f9137412ef4.

**Pull request merged**
